Myblog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^backend/', include('backend.urls')),
    url(r'^', include('web.urls')),
]

web/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from web.views import home,account
from django.urls import re_path,path

urlpatterns = [
    # url(r'^', home.index),
    path('',home.index),
    url(r'^all/(?P<article_type_id>\d+).html$', home.index, name='index'),
    path('register.html',account.register),
    path('create_check_code',account.check_code),
    path('login.html',account.login),
    path('logout.html',account.logout),
    re_path(r'^(?P<site>\w+).html$', home.home),
    re_path(r'^(?P<site>\w+)/(?P<type>((tag)|(categroy)|(data)))/(?P<val>\w+-*\w*).html$',
            home.filter),
    re_path(r'^(?P<site>\w+)/(?P<nid>\d+).html',home.detail),
]

repository/models.py
from django.db import models

# Create your models here.

class UserInfo(models.Model):
    """
    用户信息表
    """
    nid = models.BigAutoField(primary_key=True)
    username = models.CharField(max_length=32,verbose_name="用户名",unique=True)
    password = models.CharField(max_length=64,verbose_name="密码")
    nickname = models.CharField(max_length=32,verbose_name="昵称")
    email = models.EmailField(verbose_name="邮箱",unique=True)
    avatar = models.ImageField(verbose_name="头像",upload_to='static/user_avatar')
    createtime = models.DateTimeField(verbose_name="创建时间",auto_now_add=True)

    fans = models.ManyToManyField(verbose_name="粉丝",
                                  to="UserInfo",
                                  through="UserFans",   #自定义第三张表时，使用字段用于指定关系表
                                  related_name="f",
                                  through_fields= ("user","follower"),
                                  )

    class Meta:
        verbose_name_plural="用户列表"

    def __str__(self):
        return self.username

class UserFans(models.Model):
    """
    互粉表关系
    user :博主
    follow:粉丝
    """
    #related_name是反向操作时，使用的字段名，用于代替 【表名_set】
    user = models.ForeignKey(verbose_name="博主",on_delete=models.CASCADE,to="UserInfo",to_field="nid",related_name="users")
    follower = models.ForeignKey(verbose_name="粉丝",on_delete=models.CASCADE,to="UserInfo",to_field="nid",related_name="followers")
    class Meta:
        #联合唯一
        unique_together = [
            ("user","follower"),
        ]

class Blog(models.Model):
    """
    个人博客信息
    """
    bid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=60,verbose_name="个人博客标题")
    site  = models.CharField(max_length=32,verbose_name="个人博客前缀",unique=True)
    theme = models.CharField(max_length=32,verbose_name="博客主题")
    user = models.OneToOneField(to="UserInfo",to_field="nid",on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural="个人博客"

    def __str__(self):
        return self.title

class IssueInfo(models.Model):
    """
    故障单信息
    """

    uuid = models.UUIDField()
    title = models.CharField(max_length=60,verbose_name="故障标题")
    detail = models.TextField(verbose_name="故障详情")
    user = models.ForeignKey(verbose_name="提单人",to="UserInfo",to_field="nid",on_delete=models.CASCADE,related_name="user")
    processor = models.ForeignKey(verbose_name="责任人",to="UserInfo",to_field="nid",on_delete=models.CASCADE,related_name="processor",null=True,blank=True)
    status_type = [
        (1,"待处理"),
        (2,"处理中"),
        (3,"已处理"),
    ]
    status = models.IntegerField(choices=status_type)
    create_time = models.DateTimeField(verbose_name="创建时间",auto_now_add=True)
    endtime = models.DateTimeField(verbose_name="处理时间",null=True,blank=True)

    class Meta:
        verbose_name_plural="故障单信息"

    def __str__(self):
        return self.title

class Category(models.Model):
    """
    个人文章分类
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name="分类名称",max_length=32)
    blog = models.ForeignKey(verbose_name="所属博客",to="Blog",to_field="bid",on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural="个人文章分类"

class Tag(models.Model):
    """
    标签表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name="标签名称",max_length=32)
    blog = models.ForeignKey(verbose_name="所属博客",to="Blog",to_field="bid",on_delete=models.CASCADE)

class Article(models.Model):
    """
    文章表
    """
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name="文章标题",max_length=128)
    summary = models.CharField(verbose_name="文章简介",max_length=512)
    read_count = models.IntegerField(default=0)
    comment_count = models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)
    create_time = models.DateTimeField(auto_now_add=True)
    blog = models.ForeignKey(verbose_name="所属博客",to="Blog",to_field="bid",on_delete=models.CASCADE)
    category = models.ForeignKey(verbose_name="文章类型",to="Category",to_field="nid",on_delete=models.CASCADE)
    article_type_choices = [
        (1,"Python"),
        (2,"Linux"),
        (3,"Java"),
        (4,"Golang"),
    ]
    article_type_id = models.IntegerField(verbose_name="主站分类id",choices=article_type_choices,default=None)
    tag = models.ManyToManyField(
        verbose_name="文章标签",
        to="Tag",
        through="Tag2Article",

    )
    class Meta:
        verbose_name_plural="文章信息"

class Tag2Article(models.Model):
    """
    文章与标签关系表
    """

    tag = models.ForeignKey(verbose_name="标签",to="Tag",to_field="nid",on_delete=models.CASCADE)
    article = models.ForeignKey(verbose_name="文章",to="Article",to_field="nid",on_delete=models.CASCADE)

    class Meta:
        unique_together = [
            ("tag","article"),
        ]

class ArticleDetail(models.Model):
    """
    文章内容表
    """
    content = models.TextField(verbose_name="文章内容")
    article= models.ForeignKey(verbose_name="所属文章",to="Article",to_field="nid",on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural="文章内容"

class UpDown(models.Model):
    """
    文章点赞关系
    """
    article = models.ForeignKey(verbose_name="所属文章",to="Article",to_field="nid",on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name="踩或赞用户",to="UserInfo",to_field="nid",on_delete=models.CASCADE)
    up = models.BooleanField(verbose_name="是否赞")

    class Meta:
        verbose_name_plural = "文章点赞关系"
        unique_together = [
            ("article","user"),
        ]


class Comment(models.Model):
    nid = models.BigIntegerField(primary_key=True)
    content = models.CharField(verbose_name="评论内容",max_length=256)
    create_time = models.DateTimeField(auto_now_add=True)
    reply = models.ForeignKey(verbose_name="回复评论",to="self",null=True,blank=True,on_delete=models.CASCADE)
    article = models.ForeignKey(verbose_name="评论文章", to="Article", to_field="nid", on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name="评论用户", to="UserInfo", to_field="nid", on_delete=models.CASCADE)
    class Meta:
        verbose_name_plural="评论信息"

web/forms/login.py
# -*- coding: utf-8 -*-
from django import forms  # 导入表单模块
from django.core.exceptions import ValidationError
from web.forms.base import BaseForm


class LoginForm(BaseForm,forms.Form):  # 自定义表单类，并继承forms.Form

    username = forms.CharField(
        error_messages={
            "required": "用户名不能为空",
            'invalid': u'用户名格式错误',
        },

        widget=forms.TextInput(attrs={"class": "form-control"}))

    password = forms.CharField(min_length=6, widget=forms.PasswordInput(
        attrs={"class": "form-control"}),
       error_messages={
           "required": "密码不能为空",
       },
        )


    valid_code = forms.CharField(widget=forms.TextInput(
        attrs={"class": "form-control"}),
        error_messages={
            "required": "验证码不能为空",}
    )

    # 自定义方法（局部钩子）
    def clean_valid_code(self):  # 检验验证码正确；之前生成的验证码保存在了了session中
        print(self.cleaned_data)
        # print(self.request.session.get('CheckCode').upper())
        if self.cleaned_data.get('valid_code').upper() == self.request.session.get('CheckCode').upper():
            return self.cleaned_data['valid_code']
        else:
            raise ValidationError('验证码不正确')

web/views/home.py
# -*- coding: utf-8 -*-
from django.shortcuts import render,redirect
from repository import models
from django.urls import reverse
from utils.pagination import Pagination


#主页
def index(request,*args,**kwargs):
    print(request)
    print(kwargs)

    if kwargs:
        article_type_id = int(kwargs['article_type_id'])
        #在HTML中：{% url "index" article_type_id=1 %}             => all/1.html
        #在views中：reverse('index',kwargs={"article_type_id":1})  =>all/1.html
        base_url = reverse('index',kwargs=kwargs)
    else:
        article_type_id = None
        base_url = '/'

    #分页查看，必要参数：当前页码、需要展示数据的总个数
    data_count = models.Article.objects.filter(**kwargs).count() #需要展示的总个数
    page_obj = Pagination(request.GET.get('p'), data_count)  #当前页码
    #为了显示最新内容在最上面，需要加上order_by,参数加-就是倒序（desc），不加就是顺序（asc）
    article_list = models.Article.objects.filter(**kwargs).order_by('nid')[page_obj.start:page_obj.end]
    type_list = models.Article.article_type_choices
    #page_str就是分页工具最后生成的那一排a标签，要传到前端去显示
    page_str = page_obj.page_str(base_url)

    return render(request,"index.html",
                  {
                      "type_list":type_list,
                      "article_type_id":article_type_id,
                      "article_list":article_list,
                      "page_str":page_str,
                  }
                  )

def home(request,site):
    blog = models.Blog.objects.filter(site=site).select_related('user').first()
    if not blog:
        return redirect('/')
    base_url = site+".html"
    tag_list = models.Tag.objects.filter(blog=blog)
    type_list = models.Category.objects.filter(blog=blog)
    date_list = models.Article.objects.raw(
        'select nid, count(nid) as num,strftime("%Y-%m",create_time) as ctime from repository_article group by strftime("%Y-%m",create_time)')

    # article_list = models.Article.objects.filter(blog=blog).order_by("nid").all()
    data_count = models.Article.objects.filter(blog=blog).count()  # 需要展示的总个数
    page_obj = Pagination(request.GET.get('p'), data_count, per_page_count=4)  # 当前页码
    # 为了显示最新内容在最上面，需要加上order_by,参数加-就是倒序（desc），不加就是顺序（asc）
    article_list = models.Article.objects.filter(blog=blog).order_by('nid')[page_obj.start:page_obj.end]
    # page_str就是分页工具最后生成的那一排a标签，要传到前端去显示
    page_str = page_obj.page_str(base_url)
    return render(request,'home.html',{
        'blog':blog,
        "tag_list":tag_list,
        "type_list":type_list,
        "date_list":date_list,
        "article_list":article_list,
        "page_str":page_str,
    }
                  )


def filter(request,site,type,val):
    blog = models.Blog.objects.filter(site=site).select_related('user').first()
    if not blog:
        return redirect('/')
    tag_list = models.Tag.objects.filter(blog=blog)
    type_list = models.Category.objects.filter(blog=blog)
    date_list = models.Article.objects.raw(
        'select nid, count(nid) as num,strftime("%Y-%m",create_time) as ctime from repository_article group by strftime("%Y-%m",create_time)')

    if type == "tag":
        article_list = models.Article.objects.filter(blog=blog,tag=val)
    elif type == "categroy":
        article_list = models.Article.objects.filter(blog=blog,categroy_id=val)

    elif type == "data":
        #mysql数据库用下面这个
        # article_list = models.Article.objects.filter(blog=blog).extra(
        # where=['date_format(create_time,"%%Y-%%m")=%s'], params=[val, ]).all()
        #sqlite用下面这个
        article_list = models.Article.objects.filter(blog=blog).extra(
            where=['strftime("%%Y-%%m",create_time)=%s'], params=[val, ]).all()
    return render(request,'home.html',{
        'blog':blog,
        "tag_list":tag_list,
        "type_list":type_list,
        "date_list":date_list,
        "article_list":article_list
    }
                  )

def detail(request,site,nid):
    blog = models.Blog.objects.filter(site=site).first()
    if not blog:
        return redirect('/')
    base_url = "/"+site+"/"+nid+".html"
    tag_list = models.Tag.objects.filter(blog_id=blog.bid)
    type_list = models.Category.objects.filter(blog_id=blog.bid)
    date_list = models.Article.objects.raw(
        'select nid, count(nid) as num,strftime("%Y-%m",create_time) as ctime from repository_article group by strftime("%Y-%m",create_time)')

    # article = models.Article.objects.filter(blog_id=blog.bid,nid=nid).first()
    article_detail = models.ArticleDetail.objects.filter(article_id=nid).first()
    # comment_list = models.Comment.objects.filter(article_id=nid).all()
    data_count = models.Comment.objects.filter(article_id=nid).count()
    page_obj = Pagination(request.GET.get('p'), data_count)
    comment_list = models.Comment.objects.filter(article_id=nid).order_by('-nid')[page_obj.start:page_obj.end]
    #page_str就是分页工具最后生成的那一排a标签，要传到前端去显示
    page_str = page_obj.page_str(base_url)

    return render(request,'home_detail.html',
                  {
                      "blog":blog,
                      "tag_list":tag_list,
                      "type_list":type_list,
                      "date_list":date_list,
                      "article":article_detail,
                      "comment_list":comment_list,
                      "page_str":page_str,
                  })

templates/backend_article.html
{% extends "backend_layout.html" %}
{% load search %}
{% block title %}文章管理{% endblock %}
{% block css %}
    <style>
        .conditions a.active{
            background-color: #b35215;
            color: #ffffff;
        }

        .conditions a{
            display: inline-block;
            padding: 2px 5px;
            margin-left: 5px;
    }
    </style>
{% endblock %}
{% block content %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#">文章管理</a></li>
        <li class="active">文章列表</li>
    </ol>
    <div>
        <div style="border: 1px dashed #dddddd;padding: 8px;border-left: 3px solid #337ab7;">
            <i class="fa fa-search" aria-hidden="true"></i> 搜索条件
        </div>
        <div style="padding: 10px">
            <div class="conditions row clearfix" style="margin: 0;padding: 8px 0;">
                <div class="col-xs-1" style="text-align: right">

                    {% category_all arg_dict %}
                </div>
                <div class="col-xs-11">
                    {% category_combine category_list arg_dict %}
                </div>
            </div>
            <div class="conditions row clearfix" style="margin: 0;padding: 8px 0;">
                <div class="col-xs-1" style="text-align: right">
                    {% article_type_all arg_dict %}
                </div>
                <div class="col-xs-11">
                    {% article_type_combine type_list arg_dict %}
                </div>
            </div>
        </div>

        <div class="clearfix"
             style="height: 36px;line-height: 35px;padding: 0 15px;border-top: 1px solid #dddddd;background-color: #f1f0f0">
            <i class="fa fa-table" aria-hidden="true"></i>
            搜索文章({{ data_count }}篇)
            <a target="_blank" href="/backend/add-article.html" class="right"
               style="display: inline-block;padding:0 10px;background-color: #428bca;color: #ffffff;">
                <i class="fa fa-plus-circle" aria-hidden="true"></i>
                创建新文章
            </a>
        </div>


<table class="table table-bordered">
            <thead>
            <tr>
                <th>文章标题</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for row in article_list %}
                <tr nid="{{ row.nid }}">
                    <td><a href="/{{ row.blog.site }}/{{ row.nid }}.html">{{ row.title }}</a></td>
                    <td>
                        <a class="btn btn-danger btn-xs" href="/backend/delete-article-{{ row.nid }}.html">
                            <i class="fa fa-times" aria-hidden="true"></i>
                            删除
                        </a>
                        |
                        <a class="btn btn-primary btn-xs" href="/backend/edit-article-{{ row.nid }}.html">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            编辑
                        </a>
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>

        <div class="clearfix">
            <ul class="pagination right" style="margin-top: 0">
               {{ page_str }}
            </ul>
        </div>
    </div>
{% endblock %}

templates/backend_edit_article.html
{% extends 'backend_layout.html' %}
{% block css %}
    <link rel="stylesheet" href="/static/plugin/kindeditor/themes/default/default.css"/>
{% endblock %}


{% block content %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#">文章管理</a></li>
        <li class="active">编辑</li>
    </ol>

    <div>
        <form action="/backend/edit-article-{{ nid }}.html" method="post" novalidate>
            {% csrf_token %}
            <div class="form-group">
{#                label标签#}
{#                FOR属性#}
{#                功能：表示Label标签要绑定的HTML元素，你点击这个标签的时候，所绑定的元素将获取焦点。#}
{#                用法： <Label FOR="InputBox">姓名</Label><input ID="InputBox" type="text">#}
{#                ACCESSKEY属性：#}
{#                功能：表示访问Label标签所绑定的元素的热键，当您按下热键，所绑定的元素将获取焦点。#}
{#                用法： <Label FOR="InputBox" ACCESSKEY＝"N">姓名</Label><input ID="InputBox" type="text">#}
{#                局限性：accessKey属性所设置的快捷键不能与浏览器的快捷键冲突，否则将优先激活浏览器的快捷键。#}

                <label for="{{ form.title.id_for_label }}">标题 <span>{{ form.title.errors.0 }}</span></label>
                {{ form.title }}
            </div>
            <div class="form-group">
                <label for="id_summary">简介 <span>{{ form.summary.errors.0 }}</span></label>
                {{ form.summary }}
            </div>
            <div class="form-group" style="width: 100%">
                <label for="id_content">内容 <span>{{ form.content.errors.0 }}</span></label>
                {{ form.content }}
            </div>
            <div class="form-group">
                <label for="id_content">文章分类 <span>{{ form.article_type_id.errors.0 }}</span></label>
                {{ form.article_type_id }}
            </div>
            <div class="form-group">
                <label for="id_content">个人分类 <span>{{ form.category_id.errors.0 }}</span></label>
                {{ form.category_id }}
            </div>

            <div class="form-group">
                <label for="id_content">个人标签 <span>{{ form.tags.errors.0 }}</span></label>
                {{ form.tags }}
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="保 存">
            </div>
        </form>

    </div>


{% endblock %}

{% block js %}
    <script charset="utf-8" src="/static/plugin/kindeditor/kindeditor-min.js"></script>
    <script charset="utf-8" src="/static/plugin/kindeditor/lang/zh_CN.js"></script>
    <script>
        var editor;
        KindEditor.ready(function (K) {
            editor = K.create('textarea[name="content"]', {
                resizeType: 1,
                allowPreviewEmoticons: false,
                allowImageUpload: false,
                width:"100%",
                items: [
                    'fontname', 'fontsize', '|', 'forecolor', 'hilitecolor', 'bold', 'italic', 'underline',
                    'removeformat', '|', 'justifyleft', 'justifycenter', 'justifyright', 'insertorderedlist',
                    'insertunorderedlist', '|', 'emoticons', 'image', 'link']
            });
        });
    </script>
{% endblock %}

templates/backend_index.html
{% extends "backend_layout.html" %}
{% block title %}
    后台管理首页
{% endblock %}
{% block content %}
    <h1>欢迎登陆：{{ request.session.user_info.nickname }}</h1>
{% endblock %}

templates/backend_trouble_create.html
{% extends 'backend_layout.html' %}
{% block title %}创建报障单{% endblock %}
{% block css %}
    <link rel="stylesheet" href="/static/plugin/kindeditor/themes/default/default.css"/>
{% endblock %}


{% block content %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#">报障管理</a></li>
        <li class="active">添加</li>
    </ol>

    <div>
        <form action="/backend/trouble-create.html" method="post" novalidate>
            {% csrf_token %}
            <div class="form-group">
{#                label标签#}
{#                FOR属性#}
{#                功能：表示Label标签要绑定的HTML元素，你点击这个标签的时候，所绑定的元素将获取焦点。#}
{#                用法： <Label FOR="InputBox">姓名</Label><input ID="InputBox" type="text">#}
{#                ACCESSKEY属性：#}
{#                功能：表示访问Label标签所绑定的元素的热键，当您按下热键，所绑定的元素将获取焦点。#}
{#                用法： <Label FOR="InputBox" ACCESSKEY＝"N">姓名</Label><input ID="InputBox" type="text">#}
{#                局限性：accessKey属性所设置的快捷键不能与浏览器的快捷键冲突，否则将优先激活浏览器的快捷键。#}

                <label for="{{ form.title.id_for_label }}">故障标题 <span>{{ form.title.errors.0 }}</span></label>
                {{ form.title }}
            </div>
            <div class="form-group">
                <label for="id_detail">故障内容 <span>{{ form.detail.errors.0 }}</span></label>
                {{ form.detail }}
            </div>

            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="提 交">
            </div>
        </form>

    </div>


{% endblock %}

{% block js %}
    <script charset="utf-8" src="/static/plugin/kindeditor/kindeditor-min.js"></script>
    <script charset="utf-8" src="/static/plugin/kindeditor/lang/zh_CN.js"></script>
    <script>
        var editor;
        KindEditor.ready(function (K) {
            editor = K.create('textarea[name="detail"]', {
                resizeType: 1,
                allowPreviewEmoticons: false,
                allowImageUpload: false,
                width:"100%",
                items: [
                    'fontname', 'fontsize', '|', 'forecolor', 'hilitecolor', 'bold', 'italic', 'underline',
                    'removeformat', '|', 'justifyleft', 'justifycenter', 'justifyright', 'insertorderedlist',
                    'insertunorderedlist', '|', 'emoticons', 'image', 'link']
            });
        });
    </script>
{% endblock %}

templates/backend_trouble_edit.html
{% extends 'backend_layout.html' %}
{% block css %}
    <link rel="stylesheet" href="/static/plugin/kindeditor/themes/default/default.css"/>
{% endblock %}


{% block content %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#">报障管理</a></li>
        <li class="active">编辑</li>
    </ol>

    <div>
        <form action="/backend/trouble-edit-{{ nid }}.html" method="post" novalidate>
            {% csrf_token %}
             <div class="form-group">
{#                label标签#}
{#                FOR属性#}
{#                功能：表示Label标签要绑定的HTML元素，你点击这个标签的时候，所绑定的元素将获取焦点。#}
{#                用法： <Label FOR="InputBox">姓名</Label><input ID="InputBox" type="text">#}
{#                ACCESSKEY属性：#}
{#                功能：表示访问Label标签所绑定的元素的热键，当您按下热键，所绑定的元素将获取焦点。#}
{#                用法： <Label FOR="InputBox" ACCESSKEY＝"N">姓名</Label><input ID="InputBox" type="text">#}
{#                局限性：accessKey属性所设置的快捷键不能与浏览器的快捷键冲突，否则将优先激活浏览器的快捷键。#}

                <label for="{{ form.title.id_for_label }}">故障标题 <span>{{ form.title.errors.0 }}</span></label>
                {{ form.title }}
            </div>
            <div class="form-group">
                <label for="id_detail">故障内容 <span>{{ form.detail.errors.0 }}</span></label>
                {{ form.detail }}
            </div>

            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="提 交">
            </div>
        </form>

    </div>


{% endblock %}

{% block js %}
    <script charset="utf-8" src="/static/plugin/kindeditor/kindeditor-min.js"></script>
    <script charset="utf-8" src="/static/plugin/kindeditor/lang/zh_CN.js"></script>
    <script>
        var editor;
        KindEditor.ready(function (K) {
            editor = K.create('textarea[name="detail"]', {
                resizeType: 1,
                allowPreviewEmoticons: false,
                allowImageUpload: false,
                width:"100%",
                items: [
                    'fontname', 'fontsize', '|', 'forecolor', 'hilitecolor', 'bold', 'italic', 'underline',
                    'removeformat', '|', 'justifyleft', 'justifycenter', 'justifyright', 'insertorderedlist',
                    'insertunorderedlist', '|', 'emoticons', 'image', 'link']
            });
        });
    </script>
{% endblock %}

templates/home_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% block css %}{% endblock %}
    <link rel="stylesheet" href="/static/plugin/font-awesome/css/font-awesome.css">
    <link rel="stylesheet" href="/static/plugin/bootstrap/css/bootstrap.css">
    <style>
        *{
          margin: 0 0;
        }
        .header{
            width: 100%;
            height: 70px;
            background-color: #1b6d85;
            color: white;
        }
        .body_menu {
            float: left;
            width: 25%;
        }
        .article{
            float: left;
            width: 75%;
        }

    </style>
</head>
<body>
<div class="header">
    <h1>{{ blog.title }}</h1>
    <a href="/">首页</a>
    <a href="/{{ blog.site }}.html">个人首页</a>
    <a href="#">管理</a>

</div>

<div class="body">
    <div class="body_menu">
        <div class="notice">
            <div class="notice_header">公告</div>
            <div class="notice_content">
                <li>昵称：{{ blog.user.nickname }}</li>
                <li>粉丝：{{ blog.user.fans.count }}</li>
                <li>关注：{{ blog.user.f.count }}</li>
                <li>邮箱：{{ blog.user.email }}</li>
            </div>
            <div class="memo">
                我要打篮球第二季
            </div>

        </div>
        <div class="tags">
            <div class="tags_header">标签</div>
            <div class="tags_body">
                {% for item in tag_list%}
                    <a href="/{{ blog.site }}/tag/{{ item.nid }}.html"><li>{{ item.title }}({{ item.article_set.count }})</li></a>
                {% endfor %}
            </div>

        </div>
        <div class="types">
            <div class = "types_header">分类</div>
            <div class="types_body">
                {% for item in type_list %}
                    <a href="/{{ blog.site }}/categroy/{{ item.nid }}.html"><li>{{ item.title }}({{ item.article_set.count }})</li></a>
                {% endfor %}
            </div>
        </div>
        <div class="dates">
            <div class = "dates_header">时间</div>
            <div class="dates_body">
                {% for item in date_list %}
                    <a href="/{{ blog.site }}/data/{{ item.ctime }}.html"><li>{{ item.ctime }}({{ item.num }})</li></a>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="article">
        {% block content %}{% endblock %}
    </div>

</div>
{% block js %}{% endblock %}

</body>
</html>